In [11]:
import spacy
import pandas as pd

text1 = open('./no_titles/OZina_1_Lij.txt', 'r', encoding='utf-8').read()
text2 = open('./no_titles/OZina_2_Lij.txt', 'r', encoding='utf-8').read()
text3 = open('./no_titles/OZina_3_Lij.txt', 'r', encoding='utf-8').read()
text4 = open('./no_titles/OZina_4_Lij.txt', 'r', encoding='utf-8').read()
text5 = open('./no_titles/OZina_5_Lij.txt', 'r', encoding='utf-8').read()
text6 = open('./no_titles/OZina_6_Lij.txt', 'r', encoding='utf-8').read()
text7 = open('./no_titles/OZina_7_Lij.txt', 'r', encoding='utf-8').read()
text8 = open('./no_titles/OZina_8_Lij.txt', 'r', encoding='utf-8').read()
final = text1 + text2 + text3 + text4 + text5 + text6 + text7 + text8

In [12]:
# ITALIAN

nlp = spacy.load("it_core_news_sm")
doc = nlp(final)

rows = []

for token in doc:
	rows.append({
		'TEXT': token.text,
		'POS': token.pos_
	})

df_ita = pd.DataFrame(rows, columns=['TEXT', 'POS'])
df_ita.head()

      TEXT    POS
0        O  PROPN
1  Zouhaur  PROPN
2     Atif  PROPN
3        ,  PUNCT
4        o  CCONJ

In [13]:
# FRENCH

nlp = spacy.load("fr_core_news_sm")
doc = nlp(final)

rows = []

for token in doc:
	rows.append({
		'TEXT': token.text,
		'POS': token.pos_
	})

df_fra = pd.DataFrame(rows, columns=['TEXT', 'POS'])
df_fra.head()

      TEXT    POS
0        O   NOUN
1  Zouhaur  PROPN
2     Atif  PROPN
3        ,  PUNCT
4        o    ADP

In [14]:
# PORTUGUESE

nlp = spacy.load("pt_core_news_sm")
doc = nlp(final)

rows = []

for token in doc:
	rows.append({
		'TEXT': token.text,
		'POS': token.pos_
	})

df_por = pd.DataFrame(rows, columns=['TEXT', 'POS'])
df_por.head()

      TEXT    POS
0        O    DET
1  Zouhaur  PROPN
2     Atif  PROPN
3        ,  PUNCT
4        o    DET

In [ ]:
pos_mapping = {
    'VERB': 'VERB',
    'AUX':  'VERB',   # auxiliaries grouped with verbs

    'NOUN':  'NOUN',
    'PROPN': 'NOUN',  # proper nouns grouped with nouns

    'NUM':   'ADJ',  # numerals grouped with adjectives
    'ADJ': 'ADJ',

    'ADV': 'ADV',

    'PRON': 'PRON',
    'DET':  'PRON',   # determiners (e.g., articles) grouped with pronouns

	# functionals (little to no lexical meaning, but serve grammatical puprose in a sentence, connecting or relating other words)
    'ADP':   'FUNC',  # adpositions
    'CCONJ': 'FUNC',  # coordinating conjunctions
    'SCONJ': 'FUNC',  # subordinating conjunctions
    'PART':  'FUNC',  # particles

    'PUNCT': 'PUNCT',

    'INTJ': 'OTHER',
    'SYM':  'OTHER',
    'X':    'OTHER',
}

df_ita['POS_GROUPED'] = df_ita['POS'].map(pos_mapping).fillna('OTHER')
df_fra['POS_GROUPED'] = df_fra['POS'].map(pos_mapping).fillna('OTHER')
df_por['POS_GROUPED'] = df_por['POS'].map(pos_mapping).fillna('OTHER')

In [16]:
# to csv
df_ita.to_csv('postagging_italian.csv', index=False)
df_fra.to_csv('postagging_french.csv', index=False)
df_por.to_csv('postagging_portuguese.csv', index=False)