In [17]:
import spacy
import pandas as pd
import nltk
nltk.download('punkt')

text1 = open('./no_titles/OZina_1_Lij.txt', 'r', encoding='utf-8').read()
text2 = open('./no_titles/OZina_2_Lij.txt', 'r', encoding='utf-8').read()
text3 = open('./no_titles/OZina_3_Lij.txt', 'r', encoding='utf-8').read()
text4 = open('./no_titles/OZina_4_Lij.txt', 'r', encoding='utf-8').read()
text5 = open('./no_titles/OZina_5_Lij.txt', 'r', encoding='utf-8').read()
text6 = open('./no_titles/OZina_6_Lij.txt', 'r', encoding='utf-8').read()
text7 = open('./no_titles/OZina_7_Lij.txt', 'r', encoding='utf-8').read()
text8 = open('./no_titles/OZina_8_Lij.txt', 'r', encoding='utf-8').read()
final = text1 + '\n\n' + text2 + '\n\n' + text3 + '\n\n' + text4 + '\n\n' + text5 + '\n\n' + text6 + '\n\n' + text7 + '\n\n' + text8
with open('text.txt', 'w', encoding='utf-8') as f:
    f.write(final)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Sara\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [18]:
# ITALIAN

nlp = spacy.load("it_core_news_sm")
doc = nlp(final)

sentences = nltk.sent_tokenize(final, language='italian')

rows = []

for token in doc:
	rows.append({
		'SENTENCE': sentences[token.sent.start],
		'TEXT': token.text,
		'POS': token.pos_
	})

df_ita = pd.DataFrame(rows, columns=['SENTENCE', 'TEXT', 'POS'])
df_ita.head()

IndexError: list index out of range

In [12]:
# FRENCH

nlp = spacy.load("fr_core_news_sm")
doc = nlp(final)

sentences = list(doc.sents)

rows = []

for token in doc:
	rows.append({
		'SENTENCE': token.sent.text,
		'TEXT': token.text,
		'POS': token.pos_
	})

df_fra = pd.DataFrame(rows, columns=['SENTENCE', 'TEXT', 'POS'])
df_fra.head()

                                            SENTENCE     TEXT    POS
0                                                  O        O   NOUN
1  Zouhaur Atif, o zoeno arrestou pe avei ammasso...  Zouhaur  PROPN
2  Zouhaur Atif, o zoeno arrestou pe avei ammasso...     Atif  PROPN
3  Zouhaur Atif, o zoeno arrestou pe avei ammasso...        ,  PUNCT
4  Zouhaur Atif, o zoeno arrestou pe avei ammasso...        o    ADP

In [13]:
# PORTUGUESE

nlp = spacy.load("pt_core_news_sm")
doc = nlp(final)

sentences = list(doc.sents)

rows = []

for token in doc:
	rows.append({
		'SENTENCE': token.sent.text,
		'TEXT': token.text,
		'POS': token.pos_
	})

df_por = pd.DataFrame(rows, columns=['SENTENCE','TEXT', 'POS'])
df_por.head()

                                            SENTENCE     TEXT    POS
0  O Zouhaur Atif, o zoeno arrestou pe avei ammas...        O    DET
1  O Zouhaur Atif, o zoeno arrestou pe avei ammas...  Zouhaur  PROPN
2  O Zouhaur Atif, o zoeno arrestou pe avei ammas...     Atif  PROPN
3  O Zouhaur Atif, o zoeno arrestou pe avei ammas...        ,  PUNCT
4  O Zouhaur Atif, o zoeno arrestou pe avei ammas...        o    DET

In [14]:
pos_mapping = {
    'VERB': 'VERB',
    'AUX':  'VERB',   # auxiliaries grouped with verbs

    'NOUN':  'NOUN',
    'PROPN': 'NOUN',  # proper nouns grouped with nouns

    'NUM':   'ADJ',  # numerals grouped with adjectives
    'ADJ': 'ADJ',

    'ADV': 'ADV',

    'PRON': 'PRON',
    'DET':  'PRON',   # determiners (e.g., articles) grouped with pronouns

	# functionals (little to no lexical meaning, but serve grammatical puprose in a sentence, connecting or relating other words)
    'ADP':   'FUNC',  # adpositions
    'CCONJ': 'FUNC',  # coordinating conjunctions
    'SCONJ': 'FUNC',  # subordinating conjunctions
    'PART':  'FUNC',  # particles

    'PUNCT': 'PUNCT',

    'INTJ': 'OTHER',
    'SYM':  'OTHER',
    'X':    'OTHER',
}

df_ita['POS_GROUPED'] = df_ita['POS'].map(pos_mapping).fillna('OTHER')
df_fra['POS_GROUPED'] = df_fra['POS'].map(pos_mapping).fillna('OTHER')
df_por['POS_GROUPED'] = df_por['POS'].map(pos_mapping).fillna('OTHER')

In [15]:
# to csv
df_ita.to_csv('postagging_italian.csv', index=False)
df_fra.to_csv('postagging_french.csv', index=False)
df_por.to_csv('postagging_portuguese.csv', index=False)